import {useEffect,useState} from "react";
type User={username:string;role:"Admin"|"Analyst"};
type Analytics={totalCalls:number;totalDuration:number;incoming:number;outgoing:number;topCallers:{caller:string;count:number}[];cities:Record<string,number>};
type Row={id:string;callerName?:string;callerNumber?:string;receiverNumber?:string;city?:string;callDirection?:boolean;callStatus?:boolean;callDuration?:number;callCost?:string;callStartTime?:string};
async function api(path:string,options:RequestInit={}){const r=await fetch(path,{credentials:"include",...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||"Request failed");return b}
export default function App(){
const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[mode,setMode]=useState<"login"|"signup">("login"),[username,setUsername]=useState("admin"),[password,setPassword]=useState("Admin123!");
const[a,setA]=useState<Analytics|null>(null),[rows,setRows]=useState<Row[]>([]),[city,setCity]=useState(""),[caller,setCaller]=useState(""),[receiver,setReceiver]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1);
const load=async()=>{try{setError("");const q=`?city=${encodeURIComponent(city)}&caller=${encodeURIComponent(caller)}&receiver=${encodeURIComponent(receiver)}`;setA(await api("/api/analytics"+q));if(user?.role==="Admin"){const d=await api("/api/cdr?page="+page+"&limit=15"+q);setRows(d.data);setPages(d.pagination.totalPages||1)}}catch(e){setError((e as Error).message)}};
useEffect(()=>{api("/api/auth/me").then(x=>setUser(x.user)).catch(()=>{}).finally(()=>setLoading(false))},[]);
useEffect(()=>{if(user)load()},[user,page,city,caller,receiver]);
const submit=async(e:React.FormEvent)=>{e.preventDefault();try{setError("");if(mode==="signup"){await api("/api/auth/signup",{method:"POST",body:JSON.stringify({username,password})});setMode("login");setPassword("");setError("Account created. Sign in as Analyst.");return}const x=await api("/api/auth/login",{method:"POST",body:JSON.stringify({username,password})});setUser(x.user)}catch(e){setError((e as Error).message)}};
const logout=async()=>{await api("/api/auth/logout",{method:"POST"});setUser(null);setA(null)};
if(loading)return <div className="login"><div className="card auth">Loading...</div></div>;
if(!user)return <div className="login"><div className="card auth"><h1 className="brand">Call Analytics Platform</h1><p className="muted">Week 3 full-stack CDR dashboard</p><form onSubmit={submit}><div className="field"><label>Username</label><input value={username} onChange={e=>setUsername(e.target.value)}/></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></div>{error&&<div className="error">{error}</div>}<button className="primary">{mode==="login"?"Sign in":"Create Analyst account"}</button></form><button className="secondary" style={{width:"100%",marginTop:10}} onClick={()=>{setMode(mode==="login"?"signup":"login");setError("")}}>{mode==="login"?"Create Analyst account":"Back to login"}</button>{mode==="login"&&<div className="demo"><b>Demo accounts</b><br/>Admin: admin / Admin123!<br/>Analyst: analyst / Analyst123!</div>}</div></div>;
const cities=Object.entries(a?.cities||{}).sort((x,y)=>y[1]-x[1]).slice(0,8),max=cities[0]?.[1]||1;
return <><header className="top"><div><h1>Call Analytics Platform</h1><small>{user.username} · {user.role}</small></div><button className="secondary" onClick={logout}>Logout</button></header><main className="wrap">{user.role==="Analyst"&&<div className="notice"><b>Analyst access:</b> view-only analytics. CDR records are Admin-only.</div>}<div className="toolbar"><input className="filter" placeholder="City" value={city} onChange={e=>{setPage(1);setCity(e.target.value)}}/><input className="filter" placeholder="Caller number" value={caller} onChange={e=>{setPage(1);setCaller(e.target.value)}}/><input className="filter" placeholder="Receiver number" value={receiver} onChange={e=>{setPage(1);setReceiver(e.target.value)}}/><button className="secondary" onClick={()=>{setCity("");setCaller("");setReceiver("");setPage(1)}}>Clear</button></div>{error&&<div className="error">{error}</div>}<div className="grid">{[["Total calls",a?.totalCalls??0],["Total duration",(a?.totalDuration??0)+" sec"],["Incoming",a?.incoming??0],["Outgoing",a?.outgoing??0]].map(([l,v])=><div className="card stat" key={String(l)}><div className="label">{l}</div><div className="value">{v}</div></div>)}</div><div className="two"><section className="card section"><h2>Top callers</h2><div className="bars">{(a?.topCallers||[]).map(x=><div className="barrow" key={x.caller}><span>{x.caller}</span><div className="bar"><i style={{width:Math.max(5,x.count/(a?.topCallers[0]?.count||1)*100)+"%"}}/></div><b>{x.count}</b></div>)}</div></section><section className="card section"><h2>Calls by city</h2><div className="bars">{cities.map(([n,c])=><div className="barrow" key={n}><span>{n}</span><div className="bar"><i style={{width:Math.max(5,c/max*100)+"%"}}/></div><b>{c}</b></div>)}</div></section></div>{user.role==="Admin"&&<section className="card section"><h2>CDR records</h2><div className="tablewrap"><table className="table"><thead><tr><th>Caller</th><th>Receiver</th><th>City</th><th>Direction</th><th>Status</th><th>Duration</th><th>Cost</th><th>Start</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.callerNumber||r.callerName||"-"}</td><td>{r.receiverNumber||"-"}</td><td>{r.city||"-"}</td><td>{r.callDirection===true?"Incoming":"Outgoing"}</td><td>{r.callStatus===true?"Successful":"Failed"}</td><td>{r.callDuration??0}s</td><td>£{r.callCost||"0.00"}</td><td>{r.callStartTime?new Date(r.callStartTime).toLocaleString():"-"}</td></tr>)}</tbody></table></div><div className="pager"><button className="secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} / {pages}</span><button className="secondary" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>}</main></>}